# Generated by Django 3.0.5 on 2020-09-15 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200206_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date',
        ),
        migrations.AddField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
